[package]
name = "correct-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
crossbeam-channel = "0.5.6"
parking_lot = "0.12.1"
rusttype = "0.9.3"
xcb = "1.2.0"
xcb-util-cursor = "0.3.2"

[dev-dependencies]
alsa-sys = "0.3.1"
chrono = "0.4.22"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
