[package]
name = "correct-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
crossbeam-channel = "0.5.6"
parking_lot = "0.12.1"
rusttype = "0.9.3"
xcb = "1.2.0"

[dev-dependencies]
chrono = "0.4.22"
sysinfo = "0.26.7"
