[package]
name = "correct-bar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
crossbeam-channel = "0.5.6"
parking_lot = "0.12.1"
rusttype = "0.9.3"

xcb = { version = "1.2.0", optional = true }
xcb-util-cursor = { version = "0.3.2", optional = true }

wayland-client = { version = "0.31.3", optional = true }

[dev-dependencies]
alsa-sys = "0.3.1"
chrono = "0.4.22"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
dbus = "0.9.7"
libpulse-sys = "1.21.0"

[features]
default = ["x11", "wayland"]
x11 = ["xcb", "xcb-util-cursor"]
wayland = ["wayland-client"]
