[package]
name = "cb-core"
version = "0.1.0"
edition = "2024"

[dependencies]
kurbo = "0.12"
parley = "0.7.0"
peniko = "0.5"
vello = "0.6.0"
wgpu = "26.0.1"

cb-common = { path = "../cb-common" }
nalgebra = "0.34.1"
